### PR TITLE
Fix clearing of compilation errors when we expand the lambda editor

### LINKED ISSUE #1703: Bug: Fix clearing of compilation errors when we expand the lambda editor
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Fix clearing of compilation errors when we expand the lambda editor

### Steps to reproduce

Copy paste below grammar and open the derived property editor. Compile the code. It fails at compilation. You see the error in lambda editor but when you expand the lambad editor the error is cleared

### Model data

```text
Class test::class
{
  name: String[1];
  age: Number[1];
  derivedProp() {$this.name.path}: String[1];
}
```

### Environment

_No response_

### Possible solution and workaround

_No response_

### Contribution

- [X] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

closes #1703

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/87973126/205231893-092e6cbe-9ab5-45f0-9a70-75a1a998d051.mp4

### CODE REVIEW

File: packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts [hunk 1]
```diff
@@ -126,7 +126,6 @@ export class DerivedPropertyState extends LambdaEditorState {
             ? this.extractLambdaString(grammarText)
             : '',
         );
-        this.clearErrors();
```
Comment (akphi) [inline packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: I think this is intended behavior, because we change the rendering style from `standard` to `pretty` so source information from the old error might be off.

Comment (MauricioUyaguari) [reply packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: should we recomplile here if there is an existing error ? that way the user keeps the error with the updated source information?

Comment (akphi) [reply packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: I don't think the simple expand/collapse should bear the cost of recompilation. Also, it might be weird if we expand/collapse when user hasn't compile anytime, they will be caught off surprise to know this toggling cause compilation to occur. So IMO, we should leave this as is

Comment (MauricioUyaguari) [reply packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: The issue tho is that when there is an exisiting compilation error on that lambda and they expand it disappears. 
Not suggesting we do a compile everytime they toggle expand (that would be too expensive). but more: 
if there is an existing compile error on that lambda then recompile so we get the updated source information and show the correct source information.
Or maybe if we don't want to recompile, just keep the error message but remove the source info pointers as they are no longer relevant, if the user wants the updated, then they would need to hit f9 again.

File: packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts [hunk 2]
```diff
@@ -126,7 +126,7 @@ export class DerivedPropertyState extends LambdaEditorState {
...
```
Comment (MauricioUyaguari) [inline packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: Isnt this change too broad. We call `convertLambdaObjectToGrammarString` when typing so would this change not delete errors when a user fixes an error ? 
Also could we update the video to show clicking the expand button

Comment (gayathrir11) [reply packages/legend-application-studio/src/stores/editor-state/element-editor-state/ClassState.ts:129]: do you think if it makes sense to add a flag to this function which tells us if user is trying to expand the lambda editor and clearErrorSourceINformation in that case?

File: packages/legend-application-studio/src/stores/editor/editor-state/element-editor-state/ClassState.ts [hunk 3]
```diff
@@ -104,7 +104,10 @@ export class DerivedPropertyState extends LambdaEditorState {
     }
   }
 
-  *convertLambdaObjectToGrammarString(pretty: boolean): GeneratorFn<void> {
+  *convertLambdaObjectToGrammarString(
+    pretty: boolean,
+    clearErrorSourceInformation?: boolean | undefined,
```
Comment (MauricioUyaguari) [inline packages/legend-application-studio/src/stores/editor/editor-state/element-editor-state/ClassState.ts:109]: maybe the flag name should be more specific to error. I think the point of the flag is we want to keep the error. 
so maybe 
`keepError?: boolean`
then there we keep error but clear source info

File: packages/legend-graph/src/graph-manager/action/EngineError.ts [hunk 4]
```diff
@@ -16,9 +16,17 @@
...
 import type { SourceInformation } from '../action/SourceInformation.js';
+import { makeObservable, observable } from 'mobx';
 
 export class EngineError extends ApplicationError {
   sourceInformation?: SourceInformation | undefined;
+
+  constructor(message: string | undefined) {
+    super(message);
+    makeObservable(this, {
+      sourceInformation: observable,
```
Comment (MauricioUyaguari) [inline packages/legend-graph/src/graph-manager/action/EngineError.ts:27]: we want to avoid adding observable directly on the model. we could add it in its downstream usage?

Comment (MauricioUyaguari) [reply packages/legend-graph/src/graph-manager/action/EngineError.ts:31]: i meant more on the actual creation of it. so maybe we create an observe method and call it here `V1_buildCompilationError`

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]
small comment but important

File: packages/legend-query-builder/src/stores/shared/LambdaEditorState.ts [hunk 5]
```diff
@@ -115,5 +123,6 @@ export abstract class LambdaEditorState {
   abstract convertLambdaGrammarStringToObject(): GeneratorFn<void>;
   abstract convertLambdaObjectToGrammarString(
     pretty: boolean,
```
Comment (akphi) [inline packages/legend-query-builder/src/stores/shared/LambdaEditorState.ts:125]: TODO: refactor to `options?: { ... }`

File: packages/legend-query-builder/src/stores/shared/LambdaEditorState.ts [hunk 6]
```diff
@@ -69,6 +70,13 @@ export abstract class LambdaEditorState {
     this.setParserError(undefined);
   }
 
+  keepError(): void {
```
Comment (akphi) [inline packages/legend-query-builder/src/stores/shared/LambdaEditorState.ts:73]: this method seems a bit confusing, I think it's better to have an option to alter the behavior of `clearErrors` instead, e.g.

```ts
clearErrors(options: { preserveCompilationError?: boolean })
```

**Review by akphi — CHANGES_REQUESTED** [review]
nice and simple change! minor comments
