### PR TITLE
Fix: Association mapping sourceID omission and hashing issue

### LINKED ISSUE #278: Bug: Relational Association Mapping omits one field when switching between form and hacker mode
## 🐛 Bug Report

`AssociationMapping` defined under `Mapping` omits the second property, after round trip, which is syntactically incorrect.

In the code snippet below:

```
model::FirmPerson: Relational
  {
    AssociationMapping
    (
      firm[model_Person, model_Firm]: [model::Test]@FirmPerson,
      employee[model_Firm, model_Person]: [model::Test]@FirmPerson
    )
  }
```

the second property `model_Firm` in `firm` and the second property `model_Person` in `employee` are omitted:
```
model::FirmPerson: Relational
  {
    AssociationMapping
    (
      firm[model_Person]: [model::Test]@FirmPerson,
      employee[model_Firm]: [model::Test]@FirmPerson
    )
  }
```

### Step to Reproduce

1. Use the snippet below to create the models and mappings
2. Switch to form mode 
3. Switch back to text mode
4. Observe `AssociationMapping` definition inside `Mapping` each property would have the second property omitted.

<pre>
###Relational
Database model::Test
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    Legal_name VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )

  Join FirmPerson(PersonTable.firm_id = FirmTable.id)
)

###Pure
Profile model::MyExtension
{
  stereotypes: [important];
  tags: [doc];
}

Enum model::IncType
{
  Corp,
  LLC
}

Class <<model::MyExtension.important>> {model::MyExtension.doc = 'This is a model of a firm'} model::Firm extends model::LegalEntity
[
  validName: $this.legalName->startsWith('_')
]
{
  employees: model::Person[1..*];
  incType: model::IncType[1];
  employeeSize() {$this.employees->count()}: Number[1];
}

Class model::LegalEntity
{
  legalName: String[1];
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
}

Association model::FirmPerson
{
  firm: model::Firm[1];
  employee: model::Person[1];
}

###Mapping
Mapping model::NewMapping
(
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [model::Test]FirmTable.id
    )
    ~mainTable [model::Test]FirmTable
    legalName: concat([model::Test]FirmTable.Legal_name, '_LTD'),
    employees[model_Person]: [model::Test]@FirmPerson
  }
  *model::Person: Relational
  {
    ~primaryKey
    (
      [model::Test]PersonTable.id
    )
    ~mainTable [model::Test]PersonTable
    firstName: [model::Test]PersonTable.firstName,
    lastName: [model::Test]PersonTable.lastName
  }
<b>
  model::FirmPerson: Relational
  {
    AssociationMapping
    (
      firm[model_Person, model_Firm]: [model::Test]@FirmPerson,
      employee[model_Firm, model_Person]: [model::Test]@FirmPerson
    )
  }
</b>
)

###Connection
RelationalDatabaseConnection model::test
{
  store: model::Test;
  type: H2;
  specification: LocalH2
  {
    testDataSetupSqls: [
      'Drop table if exists FirmTable;\r\nDrop table if exists PersonTable;\r\nCreate Table FirmTable(id INT, Legal_Name VARCHAR(200));\r\nCreate Table PersonTable(id INT, firm_id INT, lastName VARCHAR(200), firstName VARCHAR(200));\r\nInsert into FirmTable (id, Legal_Name) values (1, \'FirmX\');\r\nInsert into FirmTable (id, Legal_Name) values (2, \'FirmY\');\r\nInsert into FirmTable (id, Legal_Name) values (3, \'FirmZ\');\r\nInsert into PersonTable (id, firm_id, lastName, firstName) values (1, 1, \'John\', \'Doe\');\r\nInsert into PersonTable (id, firm_id, lastName, firstName) values (2, 1, \'Johkiun\', \'Douip.e\');\r\nInsert into PersonTable (id, firm_id, lastName, firstName) values (3, 2, \'Jauaohn\', \'Douipe\');\r\nInsert into PersonTable (id, firm_id, lastName, firstName) values (4, 2, \'Johyyfpn\', \'Doeuid\');\r\n'
      ];
  };
  auth: DefaultH2;
}

</pre>

### Expected behavior

The syntax for `AssociationMapping` should remain the same as it is in the above snippet 

### Possible Solution

### PR DESCRIPTION
**Pull request by kshradhan**
| Q                       | A                                |
| ----------------------- | -------------------------------- |
| Fixed issues?           | Fixes #278  |
| Tests added + passed?   | Yes                              |
| Changeset added?        | Yes                              |
| Documentation PR link   |                                  |
| Any dependency changes? | No                               |

Fixes #278. 
Solves the issue where the source Id in grammar text is omitted from studio's protocol classes.
This change also requires a change in engine. PR for which is already out here: [engine-#300](https://github.com/finos/legend-engine/pull/301)

### CODE REVIEW

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts [hunk 1]
```diff
@@ -352,6 +352,12 @@ export const V1_associationSchema = createModelSchema(V1_Association, {
   name: primitive(),
   package: primitive(),
   properties: list(usingModelSchema(V1_propertySchema)),
+  // NOTE: we don't process milestoning at the moment so this is added to ensure
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts:355]: Probably we don't need this comment here, we already have the marker

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 2]
```diff
@@ -342,6 +342,7 @@ const transformClassMappingPropertyMappings = (
   values: PropertyMapping[],
   isTransformingEmbeddedPropertyMapping: boolean,
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:343]: Looking at all these flags, I start to think we can be a little bit more organized by introducing a new separate `transform context` for mapping transformation, something like:

```
class V1_MappingTransformerContext extends V1_GraphTransformerContext {
  isTransformingEmbeddedPropertyMapping: boolean;
  renderSourceId: boolean;
}
``` 

I'll put a note for this.

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 3]
```diff
@@ -463,7 +467,11 @@ const transformRelationalPropertyMapping = (
           [SOURCE_INFORMATION_KEY],
         ),
   ) as V1_RawRelationalOperationElement;
-  propertyMapping.source = undefined; // @MARKER: GRAMMAR ROUNDTRIP --- omit this information during protocol transformation as it can be interpreted while building the graph
+  // Note: renderSourceId is required to have the source information persisted in case of relationalPropertyMappings
+  // source key needs to be interpeted here for consistency between engine protcol and studio protcol
+  propertyMapping.source = renderSourceId
+    ? transformPropertyMappingSource(element.sourceSetImplementation)
+    : undefined; // @MARKER: GRAMMAR ROUNDTRIP --- need this filed to render both source and target field in roundetrip Grammar
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:474]: Let's keep the comment on the marker the same as everywhere else and move this specific comment to above/merge it with the `NOTE` section

File: packages/legend-studio/src/models/metamodels/pure/model/packageableElements/domain/PropertyReference.ts [hunk 4]
```diff
@@ -69,7 +69,9 @@ export abstract class PropertyReference
     return [
       CORE_HASH_STRUCTURE.PROPERTY_POINTER,
       this.value.name,
-      this.ownerReference.valueForSerialization,
+      this.value.owner instanceof Association
```
Comment (akphi) [inline packages/legend-studio/src/models/metamodels/pure/model/packageableElements/domain/PropertyReference.ts:72]: You're changing hash computation on `metamodel` side, where is the `protocol` counterpart?

**Review by akphi — CHANGES_REQUESTED** [review]

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts (hunk 1 above)
Comment (kshradhan) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts:355]: this comment was added to make it consistent with [this snippet]( https://github.com/kshradhan/legend-studio/blob/1686faef2a94cce45c901dd1a380d42f3a71af85/packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts#L278)

File: packages/legend-studio-manual-tests/src/__tests__/roundtrip-grammar/cases/relational-association-mapping-source-id.pure [hunk 5]
```diff
@@ -0,0 +1,70 @@
+###Relational
```
Comment (MauricioUyaguari) [inline packages/legend-studio-manual-tests/src/__tests__/roundtrip-grammar/cases/relational-association-mapping-source-id.pure:1]: does this test pass now?

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 6]
```diff
@@ -442,6 +445,7 @@ const transformRelationalPropertyMapping = (
   element: RelationalPropertyMapping,
   isTransformingEmbeddedPropertyMapping: boolean,
   context: V1_GraphTransformerContext,
+  renderSourceId: boolean,
```
Comment (MauricioUyaguari) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:448]: renderSourceId? you are not really rendering here. this is used to transfrom to protocol

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 7]
```diff
@@ -463,7 +467,11 @@ const transformRelationalPropertyMapping = (
           [SOURCE_INFORMATION_KEY],
         ),
   ) as V1_RawRelationalOperationElement;
-  propertyMapping.source = undefined; // @MARKER: GRAMMAR ROUNDTRIP --- omit this information during protocol transformation as it can be interpreted while building the graph
+  // Note: renderSourceId is required to have the source information persisted in case of relationalPropertyMappings
+  // source key needs to be interpeted here for consistency between engine protcol and studio protcol
+  propertyMapping.source = renderSourceId
+    ? transformPropertyMappingSource(element.sourceSetImplementation)
```
Comment (MauricioUyaguari) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:473]: should this be for all relational property mappings or only within association set implementations?

File: .changeset/chatty-walls-worry.md [hunk 8]
```diff
@@ -0,0 +1,6 @@
+---
+'@finos/legend-studio': patch
+'@finos/legend-studio-manual-tests': patch
+---
+
+Fixed association mapping source key omission
```
Comment (akphi) [inline .changeset/chatty-walls-worry.md:6]:
```suggestion
Fix the bug where association mapping source key is omitted when building the graph (https://github.com/finos/legend-studio/issues/278)
```

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts (hunk 1 above)
Comment (akphi) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DomainSerializationHelper.ts:355]: ah we can delete them altogether now

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 9]
```diff
@@ -464,7 +468,11 @@ const transformRelationalPropertyMapping = (
           [SOURCE_INFORMATION_KEY],
         ),
   ) as V1_RawRelationalOperationElement;
-  propertyMapping.source = undefined; // @MARKER: GRAMMAR ROUNDTRIP --- omit this information during protocol transformation as it can be interpreted while building the graph
+  // Note: isTransformingSourceId is required to have the source information persisted in case of relationalPropertyMappings
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:471]: Change this whole comment block to something like:

// NOTE: `isTransformingSourceId` is needed for the roundtrip of association relational property mapping.

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 10]
```diff
@@ -583,10 +594,14 @@ const transformOtherwiseEmbeddedRelationalPropertyMapping = (
 
 const transformXStorePropertyMapping = (
   element: XStorePropertyMapping,
+  isTransformingEmbeddedPropertyMapping: boolean,
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:597]: I don't recall we have a bug with `XStore` @MauricioUyaguari ?

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts [hunk 11]
```diff
@@ -441,7 +442,11 @@ export class V1_ProtocolToMetaModelPropertyMappingBuilder
     );
     const relationalPropertyMapping = new RelationalPropertyMapping(
       this.topParent ?? this.immediateParent,
-      propertyOwner instanceof Class // TODO: we also probably need to handle this for association mapping
+      propertyOwner instanceof Class ||
```
Comment (akphi) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts:445]: Have you tried to just create `PropertyImplicitReference` here? I don't see why we still need to have this `instanceof` check here anymore

**Review by akphi — CHANGES_REQUESTED** [review]

**Comment by akphi** [comment]
@kshradhan I did a small cleanup for `PackageableElementReference` in https://github.com/finos/legend-studio/pull/349. You might need to adjust a bit.

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts (hunk 10 above)
Comment (kshradhan) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:597]: nope there was no bug. this was to make it consistent with other methods.

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts (hunk 11 above)
Comment (kshradhan) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts:445]: Yes I tried to create one. but it took in the same set of parameters so the check was added.
otherwise it would be explicit

**Comment by kshradhan** [comment]
> @kshradhan I did a small cleanup for `PackageableElementReference` in #349. You might need to adjust a bit.

done

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts (hunk 11 above)
Comment (akphi) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts:445]: what do you mean by `it took in the same set of parameters`? what is `it`?

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts [hunk 12]
```diff
@@ -703,7 +721,11 @@ class PropertyMappingTransformer
   visit_XStorePropertyMapping(
     propertyMapping: XStorePropertyMapping,
   ): V1_PropertyMapping {
-    return transformXStorePropertyMapping(propertyMapping, this.context);
+    return transformXStorePropertyMapping(
+      propertyMapping,
+      this.isTransformingEmbeddedPropertyMapping,
```
Comment (MauricioUyaguari) [inline packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:726]: Do we need this flag? I don't think emebdded property mappings can exist as both embedded and xstore property mappings. We should default this to false if thats the case and if its not the case we need a test showing this.

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts (hunk 10 above)
Comment (MauricioUyaguari) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts:596]: see my comment below

File: packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts (hunk 11 above)
Comment (kshradhan) [reply packages/legend-studio/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts:445]: the `PropertyImplicitReference` I created for `RelationalAssociationImplementation` took in the same set of parameters

**Review by MauricioUyaguari — APPROVED** [review]

**Comment by akphi** [comment]
@MauricioUyaguari @kshradhan We will merge for now since this fixes the mentioned bug, but the cleanup will be done in https://github.com/finos/legend-studio/pull/363
