### PR TITLE
Fix: Open element in viewer mode bug fix

### LINKED ISSUE #503: Bug: Viewer mode for single entity not working
## 🐛 Bug Report

Viewer mode for single entity not working

### Step to Reproduce

- Create a project
- Create a workspace
- Open the workspace just created
- Switch to `Text Mode`
- Copy & Paste the sample grammar in the `Reproduction Code or Repo` section below
- Compile and Sync the changes
- Create a review, Commit the review and Leave when prompted
- Select the project created in step 1
- Open the project in viewer mode by clicking the button labelled: `View Project`
- Append an entity-path `/entity/model::Person` or `/entity/model::Firm` to the project's URL in the URL bar
- Press Return/Enter

### Expected behavior

The project should automatically open the appended entity and the entity-path should be stripped out from the URL

### Reproduction Code or Repo

```
Enum model::incType
{
  LLC,
  LTD
}

Class model::Person
{
  firstName: String[1];
}

Class model::Firm
{
  incType: model::incType[1];
}
```

### Possible Solution

Avoid triggering a page reload while stripping elementPath from the URL.

### Additional context

Changing the navigator's location results in a page reload which in turn clears the `ViewerStore's elementPath` piece of state  stripped from the URL, hence no element to open.

### PR DESCRIPTION
**Pull request by umarphaarook**
| Q                       | A                                |
| ----------------------- | -------------------------------- |
| Fixed issues?           | Fixes #503 |
| Tests added + passed?   | Yes                              |
| Changeset added?        | Yes                              |
| Documentation PR link   |                                  |
| Any dependency changes? | No                               |

### CODE REVIEW

File: packages/legend-application/src/stores/WebApplicationNavigator.ts [hunk 1]
```diff
@@ -59,6 +59,10 @@ export class WebApplicationNavigator implements ApplicationNavigator<string> {
     this.window.open(location, '_blank');
   }
 
+  setCurrentLocation(location: string): void {
```
Comment (akphi) [inline packages/legend-application/src/stores/WebApplicationNavigator.ts:62]: You don't need this, see above

File: .changeset/chatty-onions-eat.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+'@finos/legend-application': patch
+'@finos/legend-manual-tests': patch
+'@finos/legend-studio': patch
+---
+
+View model in Read-Only Mode (View in Project) bug fix
```
Comment (akphi) [inline .changeset/chatty-onions-eat.md:7]: Please split this changeset properly

File: packages/legend-studio/src/stores/ViewerStore.ts [hunk 3]
```diff
@@ -82,7 +82,7 @@ export class ViewerStore {
   internalizeEntityPath(params: ViewerPathParams): void {
     if (params.entityPath) {
       this.elementPath = params.entityPath;
-      this.editorStore.applicationStore.navigator.jumpTo(
+      this.editorStore.applicationStore.navigator.setCurrentLocation(
         this.editorStore.applicationStore.navigator.generateLocation(
```
Comment (akphi) [inline packages/legend-studio/src/stores/ViewerStore.ts:86]: Remove this usage of `generateLocation`

File: packages/legend-studio/src/stores/ViewerStore.ts [hunk 4]
```diff
@@ -82,7 +82,7 @@ export class ViewerStore {
   internalizeEntityPath(params: ViewerPathParams): void {
     if (params.entityPath) {
       this.elementPath = params.entityPath;
-      this.editorStore.applicationStore.navigator.jumpTo(
+      this.editorStore.applicationStore.navigator.setCurrentLocation(
```
Comment (akphi) [inline packages/legend-studio/src/stores/ViewerStore.ts:85]: use `goTo`

File: packages/legend-manual-tests/cypress/script-docs/viewermode-demo.md [hunk 5]
```diff
@@ -13,18 +13,19 @@ e.g. studio-end-to-end-test-project-prod
...
 4. Delete the workspace
 
 ## Test 2: Open not-found element
 
 1. Create a new workspace
-2. Create a new element `model::Firm` and click `Open Viewer`
-3. Verify that no element editor is opened and an error notification pops up to say the element is not found
+2. Create a new element `model::Firm`
+3. Right click on `model::Firm` and click `View in Project`
+4. Verify that no element editor is opened and an error notification pops up to say the element is not found
```
Comment (MauricioUyaguari) [inline packages/legend-manual-tests/cypress/script-docs/viewermode-demo.md:26]: Can you add a note as this only work if the changes are merged. Otherwise the element will not appear in the viewer mode

File: .changeset/chatty-onions-eat.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-application': patch
+'@finos/legend-manual-tests': patch
+'@finos/legend-studio': patch
+---
```
Comment (akphi) [inline .changeset/chatty-onions-eat.md:5]: What I meant is you need 2 changesets, 1 with no messages, 1 with a message and the package you actually put the fix on, i.e. `@finos/legend-studio`

File: .changeset/curvy-seahorses-rest.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-studio': patch
+---
+
+Bug fix for opening element in viewer mode - View in Project
```
Comment (akphi) [inline .changeset/curvy-seahorses-rest.md:5]:
```suggestion
Fix an issue with opening a particular element in viewer mode from Studio editor not working properly (#[https://github.com/finos/legend-studio/issues/503](https://github.com/finos/legend-studio/issues/503))
```

File: .changeset/curvy-seahorses-rest.md [hunk 8]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-studio': patch
+---
+
+Fix an issue with opening a particular element in viewer mode from Studio editor not working properly (#[https://github.com/finos/legend-studio/issues/503](https://github.com/finos/legend-studio/issues/503))
```
Comment (akphi) [inline .changeset/curvy-seahorses-rest.md:5]:
```suggestion
Fix an issue with opening a particular element in viewer mode from Studio editor (#[https://github.com/finos/legend-studio/issues/503](https://github.com/finos/legend-studio/issues/503))
```

File: .changeset/curvy-seahorses-rest.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-studio': patch
+---
+
+Fix an issue with opening a particular element in viewer mode from Studio editor (#[https://github.com/finos/legend-studio/issues/503](https://github.com/finos/legend-studio/issues/503))
```
Comment (akphi) [inline .changeset/curvy-seahorses-rest.md:5]:
```suggestion
Fix an issue with opening a particular element in viewer mode from Studio editor ([#503](https://github.com/finos/legend-studio/issues/503))
```

File: .changeset/curvy-seahorses-rest.md [hunk 10]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-studio': patch
+---
+
+Fix an issue with opening a particular element in viewer mode from Studio editor ([#503](https://github.com/finos/legend-studio/issues/503))
```
Comment (akphi) [inline .changeset/curvy-seahorses-rest.md:5]:
```suggestion
Fix an issue with opening a particular element in viewer mode from main editor ([#503](https://github.com/finos/legend-studio/issues/503))
```

**Comment by akphi** [comment]
@umarphaarook Thanks! Please also note my `changeset` message, next time, you can look at the existing `CHANGELOG.md` to get a better idea of our format.

**Review by akphi — APPROVED** [review]
