### PR TITLE
bug fixes

### LINKED ISSUE #533: Bug: Studio and Sdlc state become out of sync when fixing compilation error
### Reproduction Code or Repo

https://user-images.githubusercontent.com/29690824/135173527-8d8025c0-d007-4def-bfb4-0bc362f5c0dc.mov

### Step to Reproduce

Open a workspace with an existing compilation error. You will get directed to text mode. After fixing compilation error and syncing, you get the following error. Looks to be a result of studio and sdlc state becoming out of sync. 

`Unable to handle operation <EntityChange type=CREATE entityPath=model::Test classifierPath=meta::pure::metamodel::type::Class content={...} newEntityPath=null>: entity "model::Test" already exists`

### Entities to reproduce
```
[
  {
    "path": "model::Test",
    "content": {
      "_type": "class",
      "name": "Test",
      "package": "model",
      "properties": [
        {
          "multiplicity": {
            "lowerBound": 1,
            "upperBound": 1
          },
          "name": "property",
          "type": "model::NotFound"
        }
      ],
      "stereotypes": [
        {
          "profile": "meta::pure::profiles::doc",
          "value": "deprecated"
        }
      ]
    },
    "classifierPath": "meta::pure::metamodel::type::Class"
  }
]
```

### PR DESCRIPTION
**Pull request by akphi**
Fixes https://github.com/finos/legend-studio/issues/476
Fixes https://github.com/finos/legend-studio/issues/471
Fixes #533 

### Misc 
- [x] Cleanup after #505
- [x] Include `package.tsconfig.json` in `@finos/legend-graph` published content

### CODE REVIEW

File: packages/legend-studio/src/stores/EditorGraphState.ts [hunk 1]
```diff
@@ -94,6 +94,17 @@ import {
 } from '@finos/legend-application';
 import { CONFIGURATION_EDITOR_TAB } from './editor-state/ProjectConfigurationEditorState';
 
+export enum GraphBuilderStatus {
+  SUCCEEDED = 'SUCCEEDED',
+  FAILED = 'FAILED',
+  REDIRECTED_TO_TEXT_MODE = 'REDIRECTED_TO_TEXT_MODE',
+}
+
+export interface GraphBuilderReport {
```
Comment (MauricioUyaguari) [inline packages/legend-studio/src/stores/EditorGraphState.ts:103]: :(

**Review by MauricioUyaguari — APPROVED** [review]
