### PR TITLE
Fix properties getting lost in mapping editor when target id is OperationSetImplementation

### LINKED ISSUE #1012: Bug: Mapping editor drops property mappings when target set implementation is an operation
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

If the target id for a mapping is an operation when you go form mode and open the mapping all the properties are lost.
Ideally there should be no changes in the project when you open the mapping element in form mode.

### Steps to reproduce

Copy paste the below grammar in text mode and then go to form mode and open target1 mapping in form mode. You notice that the values of properties are lost.

### Model data

```text
###Pure

Class example::Target1
{

 streetHolder:example::Streets[*];
}
Class example::Streets
{
  
  streets: String[*];
}


Class example::Person
{
  address: example::Location[1];
  secondAddress: example::Location[1];

}

Class  example::Location
{
  street: String[1];
}


###Mapping
Mapping example::union::bug1
(
  
    example::Target1: Pure
  {
    ~src example::Person
    streetHolder[op]: $src,
    streetHolder[s1]: $src,
    streetHolder[s3]: $src
  }
  
   *example::Streets[op] : Operation {
      meta::pure::router::operations::union_OperationSetImplementation_1__SetImplementation_MANY_(s1, s2)
   }

 
  example::Streets[s1]: Pure
  {
    ~src example::Person
    streets: $src.address.street
  }

 example::Streets[s2]: Pure
  {
    ~src example::Person
    streets: $src.secondAddress.street
  }

 example::Streets[s3]: Pure
  {
    ~src example::Person
    streets: $src.secondAddress.street
  }
)
```

### Environment

```text
Windows
```

### Possible solution and workaround

There are two approaches to fix this.
1. Throw unsupported editor mode as the target is an Operation.
2. To actually resolve the operation setImplementations and show them in the editor.

### Contribution

- [x] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

Closes #1012 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

***Before the fix***
pic4

***After the fix***

Capture

### CODE REVIEW

**Comment by MauricioUyaguari** [comment]
I dont think this is the correct behavior. 
Since the class mapping `op` is the root set implementation for that class, we should only show op and not `s1` and `s2`. 

Below is what happens when you have `s1` as root. If you look at what the mapping editor does in that case we only show `s1`. 
```
###Pure

Class example::Target1
{

 streetHolder:example::Streets[*];
}
Class example::Streets
{
  
  streets: String[*];
}


Class example::Person
{
  address: example::Location[1];
  secondAddress: example::Location[1];

}

Class  example::Location
{
  street: String[1];
}


###Mapping
Mapping example::union::bug1
(
  
    example::Target1: Pure
  {
    ~src example::Person
    streetHolder[op]: $src
  }
  
   *example::Streets[op] : Operation {
      meta::pure::router::operations::union_OperationSetImplementation_1__SetImplementation_MANY_(s1, s2)
   }

 
  example::Streets[s1]: Pure
  {
    ~src example::Person
    streets: $src.address.street
  }

 example::Streets[s2]: Pure
  {
    ~src example::Person
    streets: $src.secondAddress.street
  }
)
```

File: packages/legend-graph/src/helpers/MappingResolutionHelper.ts [hunk 1]
```diff
@@ -155,7 +155,9 @@ export const getLeafSetImplementations = (
     return undefined;
   }
   if (setImp instanceof OperationSetImplementation) {
-    return setImp.leafSetImplementations;
+    return mapping.classMappings.filter(
```
Comment (MauricioUyaguari) [inline packages/legend-graph/src/helpers/MappingResolutionHelper.ts:158]: See my comment on the expected behavior.
I think we can just remove this if statement and return the setImpl. 
We may need to rename this function tho because it is not really fetching the leafes of setImpl.

**Review by MauricioUyaguari — DISMISSED** [review]

**Comment by MauricioUyaguari** [comment]
@gayathrir11 is this ready for review?

**Comment by gayathrir11** [comment]
> @gayathrir11 is this ready for review?

yes

File: packages/legend-studio/src/components/editor/edit-panel/mapping-editor/PurePropertyMappingEditor.tsx [hunk 2]
```diff
@@ -236,11 +238,20 @@ const ClassPropertyMappingEditor = observer(
     ) : (
       ''
     );
-    const expectedType =
+    let expectedType: Type | undefined;
+    if (
```
Comment (akphi) [inline packages/legend-studio/src/components/editor/edit-panel/mapping-editor/PurePropertyMappingEditor.tsx:242]: nice! But like @MauricioUyaguari said, we could abtract this logic out to a function and use it for `relational` as well no?

File: packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingElementDecorator.ts [hunk 3]
```diff
@@ -253,45 +253,26 @@ export class MappingElementDecorator implements SetImplementationVisitor<void> {
...
       } else if (propertyType instanceof Class) {
-        const resolvedLeafSetImps =
-          // TODO: should we try to get leaf implementation here from the root
-          // or should we just simply find all class mappings for the target class
-          // as we should not try to `understand` operation class mapping union?
-          getLeafSetImplementations(
-            setImplementation.parent,
-            property.genericType.value.getRawType(Class),
-          );
+        const rootSetImp = getRootSetImplementation(
```
[the remark this answers is not in the document]
Comment (akphi) [reply packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingElementDecorator.ts:256]: I'm not so sure about this change. When the root class mapping for a class is an Operation class mapping, the correct behavior is to show all potential leaves in the UI. With your logic here, we're losing that behavior. I think that's wrong.

**Review by akphi — CHANGES_REQUESTED** [review]

**Comment by akphi** [comment]
@gayathrir11 I'm not so sure how the video shows that way. Based on the code you wrote, I would expect to only see `op`, but here we see `op`, `s1`, and `s2`. Not sure how 😄.

File: .changeset/thin-boxes-flash.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@finos/legend-studio": patch
+---
+
+Fix properties getting lost in mapping editor when target id is `OperationSetImplementation`.
```
Comment (akphi) [inline .changeset/thin-boxes-flash.md:5]:
```suggestion
Fix properties getting lost in mapping editor when target set implementation is an `OperationSetImplementation` ([#1012](https://github.com/finos/legend-studio/issues/1012)).
```

**Comment by gayathrir11** [comment]
> @gayathrir11 I'm not so sure how the video shows that way. Based on the code you wrote, I would expect to only see `op`, but here we see `op`, `s1`, and `s2`. Not sure how 😄.

sorry forgot to update the screenshot. Which behaviour do you expect? The one in screenshot or the one which shows `op`

**Comment by akphi** [comment]
@gayathrir11 I commented on the issue to keep record of what we discussed.

File: packages/legend-studio/src/components/editor/edit-panel/mapping-editor/PropertyMappingsEditor.tsx [hunk 5]
```diff
@@ -51,13 +52,26 @@ import {
...
   EmbeddedFlatDataPropertyMapping,
+  OperationSetImplementation,
 } from '@finos/legend-graph';
 import { useApplicationStore } from '@finos/legend-application';
 import {
   setImpl_nominateRoot,
   setImpl_setRoot,
 } from '../../../../stores/graphModifier/DSLMapping_GraphModifierHelper';
 
+export const expectedReturnType = (
```
Comment (akphi) [inline packages/legend-studio/src/components/editor/edit-panel/mapping-editor/PropertyMappingsEditor.tsx:63]: --> `getExpectedReturnType`

**Comment by akphi** [comment]
Just looked at the updated video, seems like we're not on the same page about the expected behavior here. Take the following example:

```
###Pure

Class example::Target1
{

 streetHolder:example::Streets[*];
}
Class example::Streets
{
  
  streets: String[*];
}


Class example::Person
{
  address: example::Location[1];
  secondAddress: example::Location[1];

}

Class  example::Location
{
  street: String[1];
}


###Mapping
Mapping example::union::bug1
(
  
    example::Target1: Pure
  {
    ~src example::Person
    streetHolder[op]: $src // this should show up in the form editor because user specified it
    streetHolder[s3]: $src // this should show up in the form editor because user specified it
    // also because `op` is the root property mapping, `s1` and `s2` should show up as part of decoration
  }
  
   *example::Streets[op] : Operation {
      meta::pure::router::operations::union_OperationSetImplementation_1__SetImplementation_MANY_(s1, s2)
   }

 
  example::Streets[s1]: Pure
  {
    ~src example::Person
    streets: $src.address.street
  }

 example::Streets[s2]: Pure
  {
    ~src example::Person
    streets: $src.secondAddress.street
  }

 example::Streets[s3]: Pure
  {
    ~src example::Person
    streets: $src.secondAddress.street
  }
)
```

When I'm in form mode, I should see `s1`, `s2` due to decoration, but I should also see `op`, `s3` because user specified them. 

---

We don't have to do it now, but if we really want to highlight the one we recommend users using (i.e. `s1`, and `s2`), we could have another indicator. `s3` and `op` might be discouraged and have a different indicator (depends) - but not now though.

File: packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts [hunk 6]
```diff
@@ -271,6 +274,8 @@ export class PureInstanceSetImplementationState extends InstanceSetImplementatio
    * so here we make sure that we reuse existing state and only add new decorated ones
    */
   decorate(): void {
+    const propertyMappingsBeforeDecoration =
```
Comment (akphi) [inline packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts:277]: Let's not forget about `flat-data` :)

File: packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts [hunk 7]
```diff
@@ -271,9 +274,22 @@ export class PureInstanceSetImplementationState extends InstanceSetImplementatio
...
+      this.mappingElement.propertyMappings;
```
Comment (akphi) [inline packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts:278]: Why don't we make this part of `MappingElementDecorator` instead? Is that possible?

**Review by akphi — APPROVED** [review]
