### PR TITLE
Fix showing preview data for milestoned properties

### LINKED ISSUE #1884: Bug: Fix showing preview data for milestoned properties
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

If you click on `preview data` option in explorer tree of query it throws an error. Instead it should return the results back.

### Steps to reproduce

Copy paste below grammar in studio. Open the embedded query builder for the service and click on preview for any of the properties

### Model data

```text
###Data
Data data::RelationalData
{
  Relational
  #{
    default.PersonTable:
      'id,firm_id,firstName,lastName\n'+
      '1,1,John,Doe\n'+
      '2,1,Nicole,Smith\n'+
      '3,2,Time,Smith\n';

    default.FirmTable:
      'id,legal_name\n'+
      '1,Finos\n'+
      '2,Apple\n';
  }#
}


###Service
Service service::SimpleRelationalPassWithSpecialEmbeddedData
{
  pattern: '/d2c48a9c-70fa-46e3-8173-c355e774004f';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |model::Firm.all(%2021-11-12)->project([x|$x.employees.firstName, x|$x.employees.lastName, x|$x.legalName], ['Employees/First Name', 'Employees/Last Name', 'Legal Name']);
    mapping: execution::RelationalMapping;
    runtime: execution::Runtime;
  }
  testSuites:
  [
    testSuite1:
    {
      data:
      [
        connections:
        [
          connection_1:
            Relational
            #{
              default.PersonTable:
                'id,firm_id,firstName,lastName\n'+
                '1,1,John,Doe\n'+
                '2,1,Nicole,Smith\n'+
                '3,2,Time,Smith\n';

              default.FirmTable:
                'id,legal_name\n'+
                '1,Finos\n'+
                '2,Apple\n';
            }#
        ]
      ]
      tests:
      [
        test1:
        {
          serializationFormat: PURE_TDSOBJECT;
          asserts:
          [
            shouldPass:
              EqualToJson
              #{
                expected : 
                  ExternalFormat
                  #{
                    contentType: 'application/json';
                    data: '[\n  {\n    "Employees/First Name": "John",\n    "Employees/Last Name": "Doe",\n    "Legal Name": "Finos"\n  },\n  {\n    "Employees/First Name": "Nicole",\n    "Employees/Last Name": "Smith",\n    "Legal Name": "Finos"\n  },\n  {\n    "Employees/First Name": "Time",\n    "Employees/Last Name": "Smith",\n    "Legal Name": "Apple"\n  }\n]';
                  }#;
              }#,
            shouldFail:
              EqualToJson
              #{
                expected : 
                  ExternalFormat
                  #{
                    contentType: 'application/json';
                    data: '[\n  {\n    "Employees/First Name": "John",\n    "Employees/Last Name": "Doe",\n    "Legal Name": "Fino"\n  },\n  {\n    "Employees/First Name": "Nicole",\n    "Employees/Last Name": "Smith",\n    "Legal Name": "Finos"\n  },\n  {\n    "Employees/First Name": "Time",\n    "Employees/Last Name": "Smith",\n    "Legal Name": "Apple"\n  }\n]';
                  }#;
              }#
          ]
        }
      ]
    }
  ]
}


###Relational
Database store::TestDB
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    legal_name VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200)
  )

  Join FirmPerson(PersonTable.firm_id = FirmTable.id)
)


###Pure
Class <<meta::pure::profiles::temporal.businesstemporal>> model::Firm
{
  legalName: String[1];
  employees: model::Person[*];
}

Class <<meta::pure::profiles::temporal.businesstemporal>> model::Person
{
  firstName: String[1];
  lastName: String[1];
}


###Mapping
Mapping execution::RelationalMapping
(
  *model::Person: Relational
  {
    ~primaryKey
    (
      [store::TestDB]PersonTable.id
    )
    ~mainTable [store::TestDB]PersonTable
    firstName: [store::TestDB]PersonTable.firstName,
    lastName: [store::TestDB]PersonTable.lastName
  }
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [store::TestDB]FirmTable.id
    )
    ~mainTable [store::TestDB]FirmTable
    legalName: [store::TestDB]FirmTable.legal_name,
    employees[model_Person]: [store::TestDB]@FirmPerson
  }
)


###Connection
RelationalDatabaseConnection model::MyConnection
{
  store: store::TestDB;
  type: H2;
  specification: LocalH2
  {
    testDataSetupSqls: [
      'Drop table if exists FirmTable;\nDrop table if exists PersonTable;\nCreate Table FirmTable(id INT, Legal_Name VARCHAR(200));\nCreate Table PersonTable(id INT, firm_id INT, lastName VARCHAR(200), firstName VARCHAR(200));\nInsert into FirmTable (id, Legal_Name) values (1, \'FirmA\');\nInsert into FirmTable (id, Legal_Name) values (2, \'Apple\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (1, 1, \'John\', \'Doe\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (2, 2, \'Tim\', \'Smith\');\nInsert into PersonTable (id, firm_id, lastName, firstName) values (3, 3, \'Nicole\', \'Doe\');\n\n'
      ];
  };
  auth: DefaultH2;
}


###Runtime
Runtime execution::Runtime
{
  mappings:
  [
    execution::RelationalMapping
  ];
  connections:
  [
    store::TestDB:
    [
      connection_1: model::MyConnection
    ]
  ];
}
```

### Environment

_No response_

### Possible solution and workaround

_No response_

### Contribution

- [X] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

closes #1884 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/87973126/217721326-c5dc39bf-995a-43cd-bfb0-6db8278f2d77.mp4

### CODE REVIEW

**Review by YannanGao-gs — DISMISSED** [review]

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts [hunk 1]
```diff
@@ -101,20 +119,30 @@ export const buildLambdaFunction = (
...
   // build milestoning parameter(s) for getAll()
   const milestoningStereotype = getMilestoneTemporalStereotype(
     _class,
     queryBuilderState.graphManagerState.graph,
   );
-  if (milestoningStereotype) {
-    queryBuilderState.milestoningState
-      .getMilestoningImplementation(milestoningStereotype)
-      .buildGetAllParameters(getAllFunction);
+
```
Comment (YannanGao-gs) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts:127]: maybe we could document the reason why getAll() doesn't work and getAllVersion() is executable ( just in case query with getAll() will also be executable in the future )

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts [hunk 2]
```diff
@@ -101,20 +119,30 @@ export const buildLambdaFunction = (
...
+  if (milestoningStereotype && options?.isBuildingExecutionQuery === true) {
```
Comment (MauricioUyaguari) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts:128]: Again i think we will break here for regular execution against milestone classes.

**Review by MauricioUyaguari — COMMENTED** [review]
I think overall here we are changing the execution query to `allVErsion` for very execution query which is not correct. we only want this during preview data click, for anything else we should use the regular `.all` with the input dates in the query that the user has defined either through parameters or constants

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts [hunk 3]
```diff
@@ -150,5 +185,12 @@ export type LambdaFunctionBuilderOption = {
    * queryBuilderState will make the lambda function building process overrides several query values, such as the row limit.
    */
   isBuildingExecutionQuery?: boolean | undefined;
+
+  /**
+   * Set this to `true` when we construct query for execution within the app to view preview data.
+   * queryBuilderState will make the lambda function building process overrides `.all()` to `.allVersions()` if the Class
+   * is milestoned and `property` to `propertyAllVersions` if a property is milestoned.
+   */
+  isBuildingExecutionQueryToPreviewData?: boolean | undefined;
```
Comment (YannanGao-gs) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts:194]: is it possible that we give it a more generic name? We also need it for checking entitlements right?

File: .changeset/eighty-lizards-cover.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@finos/legend-query-builder': patch
+---
+
+Fix showing preview data for milestoned proeprties.
```
Comment (MauricioUyaguari) [inline .changeset/eighty-lizards-cover.md:5]: Support preview data for milestoned properties.

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts [hunk 5]
```diff
@@ -101,20 +121,35 @@ export const buildLambdaFunction = (
...
     queryBuilderState.graphManagerState.graph,
   );
-  if (milestoningStereotype) {
-    queryBuilderState.milestoningState
-      .getMilestoningImplementation(milestoningStereotype)
-      .buildGetAllParameters(getAllFunction);
+
+  if (
+    milestoningStereotype &&
+    options?.isBuildingExecutionQueryToPreviewData === true
```
Comment (MauricioUyaguari) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts:131]: no need for `=== true`

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts (hunk 3 above)
Comment (MauricioUyaguari) [reply packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts:194]: @YannanGao-gs any suggestions for the name. 
should we make it specific to milestonining? maybe like
`useAllVersionsForMilestoning` ?

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts [hunk 6]
```diff
@@ -81,45 +88,73 @@ export const buildPropertyExpressionChain = (
...
-            !TEMPORARY__disableDatePropagation &&
-            parameterValue.isPropagatedValue
-          ) {
-            // NOTE: For `bitemporal` property check if the property expression has parameters which are not instance of
-            // `INTERNAL_PropagatedValue` then pass the parameters as user explicitly changed values of either of the parameters.
+      // check if we are building the expression chain to view preview data and if the
+      // the property is milestoned. If that is the case we need to replace the
+      // `property` with `propertyAllVersions`
+      if (
+        options?.isBuildingExecutionQueryToPreviewData === true &&
```
Comment (MauricioUyaguari) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts:95]: `=== true` should not be needed

File: packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts [hunk 7]
```diff
@@ -81,45 +88,73 @@ export const buildPropertyExpressionChain = (
...
+        currentExpression.func.value.genericType.value.rawType instanceof
+          Class &&
+        currentExpression.func.value._OWNER._generatedMilestonedProperties
+          .length !== 0
+      ) {
+        const name = currentExpression.func.value.name;
+        const property =
+          currentExpression.func.value._OWNER._generatedMilestonedProperties.find(
+            (e) => e.name === `${name}AllVersions`,
```
Comment (MauricioUyaguari) [inline packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts:104]: can we move `AllVersions` to a const.

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]

**Review by MauricioUyaguari — APPROVED** [review]
