### PR TITLE
Fix runtime editor not opening when it has a `ModelChainConnection`

### LINKED ISSUE #1019: Bug: Runtime editor not opening when it has a `ModelChainConnection`
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Runtime editor wouldn't open in form mode when it has a ModelChainConnection

### Steps to reproduce

Copy paste below grammar in text mode and then go to form mode and try to open the runtime. Runtime editor wouln't open.

### Model data

```text
###ServiceStore
ServiceStore test::testServiceStoreCompilationWithSingleService1
(
  Service TestService
  (
    path : '/testService';
    method : GET;
    parameters :
    (
      serializationFormat : String ( location = query )
    );
    response : [test::gen::Trade <- test::gen::TestBinding];
    security : [];
  )
)


###ExternalFormat
SchemaSet test::tradeSchema
{
  format: FlatData;
  schemas: [
    {
      content: 'section trade: DelimitedWithHeadings\n{\n  scope.untilEof;\n  delimiter: \',\';\n  nullString: \'\';\n\n  Record\n  {\n    Product           : STRING;\n    Quantity          : INTEGER;\n    \'Trade Time\'      : DATETIME;\n    Price             : DECIMAL;\n    \'Price Ccy\'       : STRING;\n   \'Settlement Ccy\'  : STRING(optional);\n    \'Settlement Rate\' : DECIMAL(optional);\n   \'Settlement Date\' : DATE;\n   \'Confirmed At\'    : DATETIME(optional);\n   \'Expiry Date\'     : DATE(optional);\n   \'Executions\'      : INTEGER(optional);\n }\n}';
    }
  ];
}

Binding test::gen::TestBinding
{
  schemaSet: test::tradeSchema;
  contentType: 'application/x.flatdata';
  modelIncludes: [
    test::gen::Trade
  ];
}


###Pure
Class test::gen::Trade
{
  product: String[1];
  quantity: Integer[1];
  tradeTime: DateTime[1];
  price: Float[1];
  priceCcy: String[1];
  settlementCcy: String[0..1];
  settlementRate: Float[0..1];
  settlementDate: StrictDate[1];
  confirmedAt: DateTime[0..1];
  expiryDate: StrictDate[0..1];
  executions: Integer[0..1];
}


###Mapping
Mapping test::mapping
(
  *test::gen::Trade: ServiceStore
  {
    ~service [test::testServiceStoreCompilationWithSingleService1] TestService
  }
)


###Connection
ServiceStoreConnection simple::serviceStoreConnection
{
  store: test::testServiceStoreCompilationWithSingleService1;
  baseUrl: 'http://baseUrl';
}

ModelChainConnection simple::modelChainConnection
{
  mappings: [
    test::mapping
  ];
}


###Runtime
Runtime simple::runtime
{
  mappings:
  [
    test::mapping
  ];
  connections:
  [
    test::testServiceStoreCompilationWithSingleService1:
    [
      connection_1: simple::serviceStoreConnection
    ],
    ModelStore:
    [
      connection_2: simple::modelChainConnection
    ]
  ];
}
```

### Environment

```text
windows
```

### Possible solution and workaround

_No response_

### Contribution

- [ ] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

Closes #1019

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/87973126/161699148-e284e2e0-f91e-4417-bb9f-a6b9c2e1c1ed.mp4

### CODE REVIEW

File: packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts [hunk 1]
```diff
@@ -256,29 +277,28 @@ export const getRuntimeExplorerTreeData = (
...
+                ? identifiedConnection.connection.packageableConnection.value
+                    .connectionValue
+                : identifiedConnection.connection;
+            if (
+              connectionValue instanceof JsonModelConnection ||
+              connectionValue instanceof XmlModelConnection
+            ) {
+              classes = classes.concat([connectionValue.class.value]);
+            }
+          });
```
Comment (MauricioUyaguari) [inline packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts:298]: Code is kind of hard to read here. 
Could we go back to what it was but instead of `throw new UnsupportedOperationError()` returning undefined and then running a filter(isNonNullable) on the end.

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]
small changes then i can approve.
Thanks!

File: .changeset/seven-spies-rest.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@finos/legend-studio": patch
+---
+
+Fix runtime editor not opening when it has `ModelChainConnection`.
```
Comment (akphi) [inline .changeset/seven-spies-rest.md:5]:
```suggestion
Fix runtime editor not opening when it has `ModelChainConnection` ([#1019](https://github.com/finos/legend-studio/issues/1019)).
```

File: packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts [hunk 3]
```diff
@@ -200,13 +202,33 @@ export const isConnectionForModelStoreWithClass = (
   return false;
 };
 
+export const isConnectionForModelStoreWithMapping = (
```
Comment (akphi) [inline packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts:205]: Why can't we merge this with `isConnectionForModelStoreWithClass`?

File: packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts [hunk 4]
```diff
@@ -275,20 +297,23 @@ export const getRuntimeExplorerTreeData = (
...
-          const classNode = {
-            data: _class,
-            id: _class.path,
-            label: _class.name,
-          };
-          nodes.set(classNode.id, classNode);
-          addUniqueEntry(childrenIds, classNode.id);
-        });
+        classes
+          .filter((_class) => _class !== undefined)
```
Comment (akphi) [inline packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts:306]: does `.filter(Boolean)` or `.filter(isNonNullable)` work, so we don't have to do `const sourceClass = guaranteeNonNullable(_class);`?

File: packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts (hunk 3 above)
Comment (gayathrir11) [reply packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts:205]: will do that

**Review by akphi — APPROVED** [review]
