### PR TITLE
Only add properties with unique name and path in query builder

### LINKED ISSUE #1853: Bug: Query Parameters/constants windows flickering and inconsistent styling
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

When in the query editor at a certain size the panels for Paramaters and Constants flicker constantly 

Kapture 2023-01-25 at 10 44 56

Other issues: 

- [x] Upon leaving text mode in query and clicking close, user gets no feedback from the screen so there should be a loading indicator of some sort so user does not repeatedly click. 
- [ ] When you right click 'add properties' in the class explorer tree to fetch structure, it should only check if there have not been existing columns with the same name+path and if so, do not automatically add them.
- [x] There should be a clear option (brush icon) for users to remove all columns in the fetch structure 
- [ ] When the constant is a date type the path displayed should change to just the name of the type of date. For example `meta::pure::functions::date::adjust`` should just be `yesterday`. 
Original: 
image
New:
image

### Steps to reproduce

_No response_

### Model data

_No response_

### Environment

_No response_

### Possible solution and workaround

_No response_

### Contribution

- [X] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by xannem**
fixes #1853 

## Summary

- [x] Only add properties with unique name and path in query builder
Kapture 2023-02-14 at 10 36 12
- [x] Replace 'brush' icon with 'trash' icon for clarity 
image
- [x]  Allow humanize property of ID to be kept during prettify process

## How did you test this change?

- [x] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

### CODE REVIEW

**Review by YannanGao-gs — APPROVED** [review]

**Comment by YannanGao-gs** [comment]
Idk if you need to add test for filtering node

File: packages/legend-shared/src/format/FormatterUtils.ts [hunk 1]
```diff
@@ -56,6 +56,19 @@ export const TITLE_CASE_EXCEPTION_WORDS = [
   'up',
 ];
 
+export const prettyCONSTName = (value: string | undefined): string => {
+  if (!value) {
+    return '';
+  }
+  const containsId = value.slice(-2) === 'ID' || value.slice(-2) === 'Id';
```
Comment (MauricioUyaguari) [inline packages/legend-shared/src/format/FormatterUtils.ts:63]: lets move `ID` and `Id` to const. 
lets also move out `value.slice(-2)` as like valueSuffix before comparing to make the code easier to read

File: packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx [hunk 2]
```diff
@@ -298,7 +304,36 @@ const QueryBuilderExplorerContextMenu = observer(
...
+            const propertyExpression =
+              buildPropertyExpressionFromExplorerTreeNodeData(
+                childNode,
+                queryBuilderState.explorerState,
+              );
+            if (
+              queryBuilderState.fetchStructureState.implementation instanceof
+              QueryBuilderTDSState
+            ) {
+              const currentProjectColumns =
```
Comment (MauricioUyaguari) [inline packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx:318]: can't you use the `.find` function instead of map and if the projection column is found to match your condition then you filter that out. Prevents you from having to use `.every` and going through all the projection columns.

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]

File: packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx (hunk 2 above)
Comment (xannem) [reply packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx:318]: True!

**Review by MauricioUyaguari — APPROVED** [review]
