### PR TITLE
Fix recursive viewing of parent class in explorer tree of query builder

### LINKED ISSUE #1172: Disable recursive viewing of parent class in explorer tree of query builder for better user experience
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

We see the parent class recursively in the explorer tree of query builder

Capture

### Steps to reproduce

Copy paste the below grammar and execute Firm class. Try to expand the Firm class in explorer tree you keep on seeing Firm class when you expand person property.

### Model data

```text
###Relational
Database my::db
(
  Table PersonTable
  (
    NAME CHAR(200),
    FIRMID INTEGER
  )
  Table FirmTable
  (
    FIRMNAME CHAR(200),
    ID INTEGER
  )

  Join Firm_Person(PersonTable.FIRMID = FirmTable.ID)
)


###Pure
Class my::Firm
{
  legalName: String[1];
  id: Integer[1];
}

Class my::Person
{
  name: String[1];
  firmID: Integer[1];
}

Association my::Employment
{
  firm: my::Firm[*];
  employees: my::Person[*];
}


###Mapping
Mapping my::map
(
  my::Person[per1]: Relational
  {
    ~mainTable [my::db]PersonTable
    name: [my::db]PersonTable.NAME
  }
  my::Firm[fir1]: Relational
  {
    ~mainTable [my::db]FirmTable
    legalName: [my::db]FirmTable.FIRMNAME
  }

  my::Employment: Relational
  {
    AssociationMapping
    (
      firm[per1,fir1]: [my::db]@Firm_Person,
      employees[fir1,per1]: [my::db]@Firm_Person
    )
  }
)
```

### Environment

```text
Windows
```

### Possible solution and workaround

_No response_

### Contribution

- [X] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

Closes #1172 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

***Model Data for Association***
```
###Relational
Database my::db
(
  Table PersonTable
  (
    NAME CHAR(200),
    FIRMID INTEGER
  )
  Table FirmTable
  (
    FIRMNAME CHAR(200),
    ID INTEGER
  )

  Join Firm_Person(PersonTable.FIRMID = FirmTable.ID)
)


###Pure
Class my::Firm
{
  legalName: String[1];
  id: Integer[1];
}

Class my::Person
{
  name: String[1];
  firmID: Integer[1];
}

Association my::Employment
{
  firm: my::Firm[*];
  employees: my::Person[*];
}


###Mapping
Mapping my::map
(
  my::Person[per1]: Relational
  {
    ~mainTable [my::db]PersonTable
    name: [my::db]PersonTable.NAME
  }
  my::Firm[fir1]: Relational
  {
    ~mainTable [my::db]FirmTable
    legalName: [my::db]FirmTable.FIRMNAME
  }

  my::Employment: Relational
  {
    AssociationMapping
    (
      firm[per1,fir1]: [my::db]@Firm_Person,
      employees[fir1,per1]: [my::db]@Firm_Person
    )
  }
)
```
pic

### CODE REVIEW

**Comment by MauricioUyaguari** [comment]
Reviewing some of the work yannan is doing and this might actually be taken care of with the mapping algo we will be using now. 
@YannanGao-gs  could you review this PR to confirm whether we would still need this if we switch to using the mapping algorithm you are implementing via PURE? Looking at the mappings for both grammars, i think the mapping algo would take care of this.

**Comment by YannanGao-gs** [comment]
> Reviewing some of the work yannan is doing and this might actually be taken care of with the mapping algo we will be using now. @YannanGao-gs could you review this PR to confirm whether we would still need this if we switch to using the mapping algorithm you are implementing via PURE? Looking at the mappings for both grammars, i think the mapping algo would take care of this.

The mapping algorithm won't avoid loop. We have to do it manually if this is needed.

**Comment by YannanGao-gs** [comment]
MappingAnalysisResult

- model data with association 

```
{
    "mappedEntities": [
        {
            "name": "my::Person",
            "properties": [
                {
                    "name": "name"
                },
                {
                    "name": "firm",
                    "entityName": "my::Firm"
                }
            ],
            "nameToProperty": {}
        },
        {
            "name": "my::Firm",
            "properties": [
                {
                    "name": "employees",
                    "entityName": "my::Person"
                },
                {
                    "name": "legalName"
                }
            ],
            "nameToProperty": {}
        }
    ],
    "nameToEntity": {}
}
```

- model data for non-assocation
```
{
    "mappedEntities": [
        {
            "name": "my::Person",
            "properties": [
                {
                    "name": "id"
                },
                {
                    "name": "name"
                },
                {
                    "name": "firm",
                    "entityName": "my::Firm"
                }
            ],
            "nameToProperty": {}
        },
        {
            "name": "my::Firm",
            "properties": [
                {
                    "name": "name"
                },
                {
                    "name": "person",
                    "entityName": "my::Person"
                },
                {
                    "name": "firmId"
                }
            ],
            "nameToProperty": {}
        }
    ],
    "nameToEntity": {}
}
```
- inheritance model above 

```
{
    "mappedEntities": [
        {
            "name": "model::Firm",
            "properties": [
                {
                    "name": "employees",
                    "entityName": "model::Person"
                }
            ],
            "nameToProperty": {}
        },
        {
            "name": "model::LegalEntity",
            "properties": [
                {
                    "name": "employees",
                    "entityName": "model::Person"
                },
                {
                    "name": "firm",
                    "entityName": "@model::Firm",
                    "subType": "model::Firm"
                }
            ],
            "nameToProperty": {}
        },
        {
            "name": "@model::Firm",
            "properties": [
                {
                    "name": "employees",
                    "entityName": "model::Person"
                }
            ],
            "nameToProperty": {}
        },
        {
            "name": "model::Person",
            "properties": [
                {
                    "name": "firms",
                    "entityName": "model::Firm"
                },
                {
                    "name": "lastName"
                },
                {
                    "name": "firstName"
                }
            ],
            "nameToProperty": {}
        }
    ],
    "nameToEntity": {}
}
```

**Comment by akphi** [comment]
@gayathrir11 Let's wait for @YannanGao-gs #1186 to figure out better specs for this

**Comment by akphi** [comment]
@gayathrir11 I think we can address this now as #1186 is merged

**Comment by MauricioUyaguari** [comment]
> @gayathrir11 I think we can address this now as #1186 is merged

@gayathrir11 @YannanGao-gs  yes, let's please ensure this is taken care of now that mapping analytics has been merged.

**Comment by akphi** [comment]
@gayathrir11 there's a breaking test

**Comment by YannanGao-gs** [comment]
Looks good to me

File: packages/legend-application-query/src/stores/QueryBuilderExplorerState.ts [hunk 1]
```diff
@@ -370,6 +372,14 @@ export const getQueryBuilderPropertyNodeData = (
     isPartOfDerivedPropertyBranch,
     mappingNodeData,
   );
+  if (
```
Comment (akphi) [inline packages/legend-application-query/src/stores/QueryBuilderExplorerState.ts:375]: I think we should do the analytics differently:
1. We know for association case the loop is of size 2, so we should add that analytics together with the fact that the property comes from `propertiesFromAssociations`, so we would have something like this

```


> Firm
    > employees: Person
        // firm: Firm --> we should not show this
        name
        age

```
2. We should not even generate the node, instead of using `mapped` flag to show/hide it, that's not the purpose of the flag

**Review by akphi — CHANGES_REQUESTED** [review]

**Review by akphi — APPROVED** [review]
