### PR TITLE
Fix creating new milestoned query from dataspace

### LINKED ISSUE #1315: Bug: Query Builder opens misconfigured milestone query when coming from dataspace diagram
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

When opening a milestone class from the dataspace diagram, the usual logic to generate milestone query is not evoked causing a query that does not execute nor gives the user a chance to fix it. 

### Steps to reproduce

- Open dataspace with milestone class in diagram
- double click on milestone class in diagram
- query builder opens the milestone class and does not have a date generated. When executing we get no date error
- workaround right now is to change classes and come back to the original class which fixes the issue

- also make sure opening to query builder on milestone class with url opens correctly

### Model data

_No response_

### Environment

_No response_

### Possible solution and workaround

_No response_

### Contribution

- [ ] I would like to work on the fix for this issue

### PR DESCRIPTION
**Pull request by gayathrir11**
## Summary

closes #1315 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

### CODE REVIEW

**Comment by YannanGao-gs** [comment]
@gayathrir11  Looks good to me :)

File: packages/legend-application-query/src/stores/QueryEditorStore.ts [hunk 1]
```diff
@@ -455,10 +456,6 @@ export class CreateQueryEditorStore extends QueryEditorStore {
           : [],
       );
     }
-
-    // initialize query builder state after setting up
```
Comment (MauricioUyaguari) [inline packages/legend-application-query/src/stores/QueryEditorStore.ts:459]: why are we removing these lines ?

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]

File: packages/legend-application-query/src/stores/QueryEditorStore.ts [hunk 2]
```diff
@@ -443,8 +443,9 @@ export class CreateQueryEditorStore extends QueryEditorStore {
...
     );
     if (this.classPath) {
-      this.queryBuilderState.querySetupState._class =
-        this.queryBuilderState.graphManagerState.graph.getClass(this.classPath);
+      this.queryBuilderState.changeClass(
+        this.queryBuilderState.graphManagerState.graph.getClass(this.classPath),
+      );
       this.queryBuilderState.querySetupState.setClassIsReadOnly(true);
     } else {
       this.queryBuilderState.querySetupState._class = getNullableFirstElement(
```
Comment (MauricioUyaguari) [inline packages/legend-application-query/src/stores/QueryEditorStore.ts:451]: what happens if the class selected here is milestoned. Should we also use the `changeClass` method here

**Review by MauricioUyaguari — CHANGES_REQUESTED** [review]

**Review by MauricioUyaguari — APPROVED** [review]
